[package]
name = "VoxelARPG_Bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13.2", features = ["default"] }
wgpu = "0.19.4"
ron = "0.6.4"
rand = "0.8.4"

[lib]
crate-type = ["cdylib", "rlib"]
